server:
  port: 9999

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/userdb?currentSchema=userdb
    username: postgres
    password: postgress
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  session:
    jdbc:
      initialize-schema: always
